version: '2'
services:
    circuit-app:
        image: circuit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://circuit-mysql:3306/circuit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    circuit-mysql:
        extends:
            file: mysql.yml
            service: circuit-mysql
